--hg = hg or {}
--
--local bandanamat = Material("mats_jack_gmod_sprites/respirator_vignette.png")
--
--hg.Accessories = {
--	["none"] = {},
--
--    ["eyeglasses"] = {
--        model = "models/captainbigbutt/skeyler/accessories/glasses01.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = { Vector(3,-2.9,0), Angle(0,-70,-90), .9},
--        fempos = {Vector(2.1,-2.7,0),Angle(0,-70,-90),.8},
--        skin = 0,
--        norender = true,
--        placement = "face"
--    },
--
--    ["bugeye sunglasses"] = {
--        model = "models/captainbigbutt/skeyler/accessories/glasses02.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(2.9,-2.2,0),Angle(0,-70,-90),.9},
--        fempos = {Vector(2.9,-3.2,0),Angle(0,-70,-90),.8},
--        skin = 0,
--        norender = true,
--        placement = "face"
--    },
--
--    ["bugeye sunglasses"] = {
--        model = "models/captainbigbutt/skeyler/accessories/glasses04.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(2.2,-3.3,0),Angle(0,-70,-90),.9},
--        fempos = {Vector(2.2,-3.3,0),Angle(0,-70,-90),.8},
--        skin = 0,
--        norender = true,
--        placement = "face"
--    },
--
--    ["aviators"] = {
--        model = "models/arctic_nvgs/aviators.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.7,0,0),Angle(0,-80,-90),1},
--        fempos = {Vector(0.25,0,0),Angle(0,-85,-90),.95},
--        skin = 0,
--        norender = true,
--        placement = "face",
--        bPointShop = true,
--        isdpoint = true,
--        price = 500,
--        vpos = Vector(0,0,0)
--    },
--
--    ["nerd glasses"] = {
--        model = "models/gmod_tower/klienerglasses.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(2.8,-2.2,0),Angle(0,-80,-90),1},
--        fempos = {Vector(2.5,-2.5,0),Angle(0,-85,-90),.95},
--        skin = 0,
--        norender = true,
--        placement = "face"
--    },
--
--    ["headphones"] = {
--        model = "models/gmod_tower/headphones.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(3.6,-1,0),Angle(0,-80,-90),.85},
--        fempos = {Vector(2.4,-1,0),Angle(0,-85,-90),.8},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["baseball cap"] = {
--        model = "models/gmod_tower/jaseballcap.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5,0,0),Angle(0,-75,-90), 1.12},
--        fempos = {Vector(4,-0.1,0),Angle(0,-75,-90), 1.125},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["fedora"] = {
--        model = "models/captainbigbutt/skeyler/hats/fedora.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5.5,-0.2,0),Angle(0,-80,-90), 0.7},
--        fempos = {Vector(4.5,-0.2,0),Angle(0,-75,-90), 0.7},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["stetson"] = {
--        model = "models/captainbigbutt/skeyler/hats/cowboyhat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(6.2,0.6,0),Angle(0,-60,-90), 0.7},
--        fempos = {Vector(5.2,0.5,0),Angle(0,-65,-90), 0.65},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["straw hat"] = {
--        model = "models/captainbigbutt/skeyler/hats/strawhat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5.2,-0.4,0),Angle(0,-70,-90), 0.85},
--        fempos = {Vector(4.5,-0.5,0),Angle(0,-75,-90), 0.8},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["sun hat"] = {
--        model = "models/captainbigbutt/skeyler/hats/sunhat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(4.2,2,0),Angle(0,-90,-90), 0.8},
--        fempos = {Vector(3.4,2,0),Angle(0,-90,-90), 0.75},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["bling cap"] = {
--        model = "models/captainbigbutt/skeyler/hats/zhat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(3.9,0.1,0),Angle(0,-80,-90), 0.75},
--        fempos = {Vector(3.5,0.2,0),Angle(-10,-80,-90), 0.75},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["top hat"] = {
--        model = "models/player/items/humans/top_hat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0,-1.5,0),Angle(0,-80,-90), 1},
--        fempos = {Vector(-0.8,-1.8,0),Angle(0,-80,-90), 1},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["backpack"] = {
--        model = "models/makka12/bag/jag.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-3,0,0),Angle(0,90,90),.75},
--        fempos = {Vector(-3,-1,0),Angle(0,90,90),.6},
--        skin = 0,
--        norender = false,
--        placement = "spine"
--    },
--
--    ["backpack hellokitty"] = {
--        model = "models/gleb/backpack_pink.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-7.5,5,0),Angle(0,80,90),1},
--        fempos = {Vector(-8,3,0),Angle(0,80,90),0.9},
--        skin = 0,
--        norender = false,
--        placement = "spine",
--        bPointShop = true,
--        isdpoint = true,
--        price = 250,
--        vpos = Vector(0,0,0)
--    },
--
--    ["kickme sticker"] = {
--        model = "models/gleb/kickme.mdl",
--        bone = "ValveBiped.Bip01_Pelvis",
--        malepos = {Vector(0,4,-6.8),Angle(-75,-90,0),1},
--        fempos = {Vector(0,4,-5.8),Angle(-65,-90,0),1},
--        skin = 0,
--        norender = false,
--        placement = "spine",
--        bonemerge = true,
--    },
--
--    ["nerd tooths"] = {
--        model = "models/gleb/nerd.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(3.3,-0.4,0),Angle(0,-85,-90),1},
--        fempos = {Vector(1.9,-0.8,0),Angle(0,-85,-90),.95},
--        skin = 0,
--        norender = true,
--        placement = "spine",
--        bonemerge = true,
--    },
--
--    ["purse"] = {
--        model = "models/props_c17/BriefCase001a.mdl",
--        bone = "ValveBiped.Bip01_Spine1",
--        malepos = {Vector(-7,1,7),Angle(0,90,100),.5},
--        fempos = {Vector(-7,0,7),Angle(0,90,100),.5},
--        skin = 0,
--        norender = false,
--        placement = "spine"
--    },
--    --CAPS
--    ["zcity cap"] = {
--        model = "models/gleb/zcap.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5,0.4,0),Angle(180,105,90),1},
--        fempos = {Vector(3.5,0.2,0),Angle(180,105,90),1},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["gray cap"] = {
--        model = "models/modified/hat07.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5,0.4,0),Angle(180,105,90),1},
--        fempos = {Vector(3.5,0.2,0),Angle(180,105,90),1},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["light gray cap"] = {
--        model = "models/modified/hat07.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5,0.4,0),Angle(180,105,90),1},
--        fempos = {Vector(3.5,0.2,0),Angle(180,105,90),1},
--        skin = 2,
--        norender = true,
--        placement = "head"
--    },
--
--    ["light gray cap"] = {
--        model = "models/modified/hat07.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5,0.4,0),Angle(180,105,90),1},
--        fempos = {Vector(3.5,0.2,0),Angle(180,105,90),1},
--        skin = 2,
--        norender = true,
--        placement = "head"
--    },
--
--    ["white cap"] = {
--        model = "models/modified/hat07.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5,0.4,0),Angle(180,105,90),1},
--        fempos = {Vector(3.5,0.2,0),Angle(180,105,90),1},
--        skin = 3,
--        norender = true,
--        placement = "head"
--    },
--
--    ["green cap"] = {
--        model = "models/modified/hat07.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5,0.5,0.1),Angle(180,105,90),1},
--        fempos = {Vector(3.5,0.2,0),Angle(180,105,90),1},
--        skin = 4,
--        norender = true,
--        placement = "head"
--    },
--
--    ["dark green cap"] = {
--        model = "models/modified/hat07.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5,0.4,0),Angle(180,105,90),1},
--        fempos = {Vector(3.5,0.2,0),Angle(180,105,90),1},
--        skin = 5,
--        norender = true,
--        placement = "head"
--    },
--
--    ["brown cap"] = {
--        model = "models/modified/hat07.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5,0.4,0),Angle(180,105,90),1},
--        fempos = {Vector(3.5,0.2,0),Angle(180,105,90),1},
--        skin = 6,
--        norender = true,
--        placement = "head"
--    },
--
--    ["blue cap"] = {
--        model = "models/modified/hat07.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(5,0.4,0),Angle(180,105,90),1},
--        fempos = {Vector(3.5,0.2,0),Angle(180,105,90),1},
--        skin = 7,
--        norender = true,
--        placement = "head"
--    },
--    -- FaceMasks
--    ["bandana"] = {
--        model = "models/modified/bandana.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(-1,-0.8,0),Angle(180,105,90),1},
--        fempos = {Vector(-2,-1.2,0),Angle(180,105,90),.9},
--        skin = 0,
--        norender = true,
--        placement = "face",
--        ScreenSpaceEffects = function()
--            -- DrawColorModify(AviatorColor)
--            surface.SetMaterial(bandanamat)
--            surface.SetDrawColor(255,255,255)
--            surface.DrawTexturedRect(-1,0,ScrW()*1.01,ScrH()*1.2)
--         end
--    },
--
--    ["arctic_balaclava"] = {
--        model = "models/d/balaklava/arctic_reference.mdl",
--        femmodel = "models/distac/feminine_mask.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,-0.95,0),Angle(180,100,90),1.1},
--        fempos = {Vector(-1,-0.8,0),Angle(180,105,90),1.05},
--        skin = 0,
--        norender = true,
--        disallowinapperance = true,
--        bonemerge = true
--    },
--
--    ["phoenix_balaclava"] = {
--        model = "models/d/balaklava/phoenix_balaclava.mdl",
--        femmodel = "models/distac/feminine_mask.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.6,-0.95,0),Angle(180,100,90),0.95},
--        fempos = {Vector(-0.6,-0.6,0),Angle(180,100,90),0.95},
--        skin = 0,
--        norender = true,
--        disallowinapperance = true,
--        bonemerge = true
--    },
--    -- scarfs
--    ["white scarf"] = {
--        model = "models/sal/acc/fix/scarf01.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-18,8,0),Angle(0,75,90),1},
--        fempos = {Vector(-18,5.5,0),Angle(0,80,90),.9},
--        skin = 0,
--        norender = false,
--        placement = "torso"
--    },
--
--    ["gray scarf"] = {
--        model = "models/sal/acc/fix/scarf01.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-18,8,0),Angle(0,75,90),1},
--        fempos = {Vector(-18,5.5,0),Angle(0,80,90),.9},
--        skin = 1,
--        norender = false,
--        placement = "torso"
--    },
--
--    ["black scarf"] = {
--        model = "models/sal/acc/fix/scarf01.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-18,8,0),Angle(0,75,90),1},
--        fempos = {Vector(-18,5.5,0),Angle(0,80,90),.9},
--        skin = 2,
--        norender = false,
--        placement = "torso"
--    },
--
--    ["blue scarf"] = {
--        model = "models/sal/acc/fix/scarf01.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-18,8,0),Angle(0,75,90),1},
--        fempos = {Vector(-18,5.5,0),Angle(0,80,90),.9},
--        skin = 3,
--        norender = false,
--        placement = "torso"
--    },
--
--    ["red scarf"] = {
--        model = "models/sal/acc/fix/scarf01.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-18,8,0),Angle(0,75,90),1},
--        fempos = {Vector(-18,5.5,0),Angle(0,80,90),.9},
--        skin = 4,
--        norender = false,
--        placement = "torso"
--    },
--
--    ["green scarf"] = {
--        model = "models/sal/acc/fix/scarf01.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-18,8,0),Angle(0,75,90),1},
--        fempos = {Vector(-18,5.5,0),Angle(0,80,90),.9},
--        skin = 5,
--        norender = false,
--        placement = "torso"
--    },
--
--    ["pink scarf"] = {
--        model = "models/sal/acc/fix/scarf01.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-18,8,0),Angle(0,75,90),1},
--        fempos = {Vector(-18,5.5,0),Angle(0,80,90),.9},
--        skin = 6,
--        norender = false,
--        placement = "torso"
--    },
--    -- earmuffs
--    ["red earmuffs"] = {
--        model = "models/modified/headphones.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(2.8,-1,0),Angle(180,105,90),1},
--        fempos = {Vector(1.8,-1,0),Angle(180,105,90),0.95},
--        skin = 0,
--        norender = true,
--        placement = "ears"
--    },
--
--    ["pink earmuffs"] = {
--        model = "models/modified/headphones.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(2.8,-1,0),Angle(180,105,90),1},
--        fempos = {Vector(1.8,-1,0),Angle(180,105,90),0.95},
--        skin = 1,
--        norender = true
--    },
--
--    ["green earmuffs"] = {
--        model = "models/modified/headphones.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(2.8,-1,0),Angle(180,105,90),1},
--        fempos = {Vector(1.8,-1,0),Angle(180,105,90),0.95},
--        skin = 2,
--        norender = true,
--        placement = "ears"
--    },
--
--    ["yellow earmuffs"] = {
--        model = "models/modified/headphones.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(2.8,-1,0),Angle(180,105,90),1},
--        fempos = {Vector(1.8,-1,0),Angle(180,105,90),0.95},
--        skin = 3,
--        norender = true,
--        placement = "ears"
--    },
--    -- fedoras
--
--    ["gray fedora"] = {
--        model = "models/modified/hat01_fix.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(3.8,0.2,0),Angle(180,105,90),1},
--        fempos = {Vector(3,0.2,0),Angle(180,105,90),1},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["black fedora"] = {
--        model = "models/modified/hat01_fix.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(3.8,0.2,0),Angle(180,105,90),1},
--        fempos = {Vector(3,0.2,0),Angle(180,105,90),1},
--        skin = 1,
--        norender = true,
--        placement = "head"
--    },
--
--    ["white fedora"] = {
--        model = "models/modified/hat01_fix.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(3.8,0.2,0),Angle(180,105,90),1},
--        fempos = {Vector(3,0.2,0),Angle(180,105,90),1},
--        skin = 2,
--        norender = true,
--        placement = "head"
--    },
--
--    ["beige fedora"] = {
--        model = "models/modified/hat01_fix.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(3.8,0.2,0),Angle(180,105,90),1},
--        fempos = {Vector(3,0.2,0),Angle(180,105,90),1},
--        skin = 3,
--        norender = true,
--        placement = "head"
--    },
--
--    ["black/red fedora"] = {
--        model = "models/modified/hat01_fix.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(3.8,0.2,0),Angle(180,105,90),1},
--        fempos = {Vector(3,0.2,0),Angle(180,105,90),1},
--        skin = 5,
--        norender = true,
--        placement = "head"
--    },
--
--    ["blue fedora"] = {
--        model = "models/modified/hat01_fix.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(3.8,0.2,0),Angle(180,105,90),1},
--        fempos = {Vector(3,0.2,0),Angle(180,105,90),1},
--        skin = 7,
--        norender = true,
--        placement = "head"
--    },
--    -- beanies
--
--    ["striped beanie"] = {
--        model = "models/modified/hat03.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(4,0,0),Angle(180,105,90),1},
--        fempos = {Vector(3,0.2,0),Angle(180,105,90),1},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["striped beanie"] = {
--        model = "models/modified/hat03.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(4,0,0),Angle(180,105,90),1},
--        fempos = {Vector(3.8,0.2,0),Angle(180,105,90),1},
--        skin = 0,
--        norender = true,
--        placement = "head"
--    },
--
--    ["periwinkle beanie"] = {
--        model = "models/modified/hat03.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(4,0,0),Angle(180,105,90),1},
--        fempos = {Vector(3.8,0.2,0),Angle(180,105,90),1},
--        skin = 1,
--        norender = true,
--        placement = "head"
--    },
--
--    ["fuschia beanie"] = {
--        model = "models/modified/hat03.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(4,0,0),Angle(180,105,90),1},
--        fempos = {Vector(3.8,0.2,0),Angle(180,105,90),1},
--        skin = 2,
--        norender = true,
--        placement = "head"
--    },
--
--    ["white beanie"] = {
--        model = "models/modified/hat03.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(4,0,0),Angle(180,105,90),1},
--        fempos = {Vector(3.8,0.2,0),Angle(180,100,90),1},
--        skin = 3,
--        norender = true,
--        placement = "head"
--    },
--
--    ["gray beanie"] = {
--        model = "models/modified/hat03.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(4,0,0),Angle(180,105,90),1},
--        fempos = {Vector(3.8,0.2,0),Angle(180,100,90),1},
--        skin = 4,
--        norender = true,
--        placement = "head"
--    },
--    -- backpacks
--    ["large red backpack"] = {
--        model = "models/modified/backpack_1.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-7.5,5.2,0),Angle(0,80,90),1},
--        fempos = {Vector(-8,4,0),Angle(0,80,90),0.9},
--        skin = 0,
--        norender = false,
--        placement = "spine"
--    },
--
--    ["large gray backpack"] = {
--        model = "models/modified/backpack_1.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-7.5,5.2,0),Angle(0,80,90),1},
--        fempos = {Vector(-8,4,0),Angle(0,80,90),0.9},
--        skin = 1,
--        norender = false,
--        placement = "spine"
--    },
--
--    ["medium backpack"] = {
--        model = "models/modified/backpack_3.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-7.5,4,0),Angle(0,80,90),1},
--        fempos = {Vector(-8,3,0),Angle(0,80,90),0.9},
--        skin = 0,
--        norender = false,
--        placement = "spine"
--    },
--
--    ["medium gray backpack"] = {
--        model = "models/modified/backpack_3.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(-7.5,4,0),Angle(0,80,90),1},
--        fempos = {Vector(-8,3,0),Angle(0,80,90),0.9},
--        skin = 1,
--        norender = false,
--        placement = "spine"
--    },
--
--    ["monokl"] = {
--        model = "models/distac/monokl.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(4.05,-4.8,-1.3),Angle(180,100,90),1},
--        fempos = {Vector(-1,-0.8,0),Angle(180,105,90),1},
--        skin = 0,
--        norender = true,
--        bonemerge = false,
--        placement = "face",
--        bPointShop = true,
--        isdpoint = true,
--        price = 200,
--        vpos = Vector(0,0,69)
--    },
--    
--    ["china hat"] = {
--        model = "models/distac/china_hat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(4.5,-0.35,0),Angle(180,100,90),1},
--        fempos = {Vector(3,-0.8,0),Angle(180,105,90),1},
--        skin = 0,
--        norender = true,
--        bonemerge = true,
--        placement = "head",
--        bPointShop = true,
--        isdpoint = false,
--        price = 200,
--        vpos = Vector(0,0,0)
--    },
--
--    ["helicopter cap"] = {
--        model = "models/distac/cap_helecopterkid.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(-70,-13.5,0),Angle(180,100,90),1.1},
--        fempos = {Vector(-63,-18.5,0),Angle(180,105,90),1},
--        skin = 0,
--        norender = true,
--        bonemerge = false,
--        placement = "head",
--        bPointShop = true,
--        isdpoint = false,
--        price = 100,
--        vpos = Vector(0,0,69)
--    },
--    
--    ["welding glasses"] = {
--        model = "models/distac/glassis_welding glasses.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,-0.95,0),Angle(180,100,90),1},
--        fempos = {Vector(0,0,0),Angle(0,0,0),1},
--        skin = 0,
--        norender = true,
--        bonemerge = true,
--        placement = "face",
--        bPointShop = true,
--        isdpoint = false,
--        price = 250,
--        vpos = Vector(0,0,69)
--    },
--
--    ["big glasses"] = {
--        model = "models/distac/big_ahhh_glassis.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,-0.95,0),Angle(180,100,90),1},
--        fempos = {Vector(0,0,0),Angle(0,0,0),1},
--        skin = 0,
--        norender = true,
--        bonemerge = true,
--        placement = "face",
--        flex = true,
--        bPointShop = true,
--        isdpoint = false,
--        price = 500,
--        vpos = Vector(0,0,69)
--    },
--
--    ["glasses with nose"] = {
--        model = "models/distac/glasses_with_mustache.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,-0.95,0),Angle(180,100,90),1},
--        fempos = {Vector(0,0,0),Angle(0,0,0),1},
--        skin = 0,
--        norender = true,
--        bonemerge = true,
--        placement = "face",
--        flex = true,
--        bPointShop = true,
--        isdpoint = true,
--        price = 300,
--        vpos = Vector(0,0,69)
--    },
--
--    ["glasses fmf"] = {
--        model = "models/distac/street_kid_fmf.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,-0.95,0),Angle(180,100,90),1},
--        fempos = {Vector(0,0,0),Angle(0,0,0),1},
--        skin = 0,
--        norender = true,
--        bonemerge = true,
--        placement = "face",
--        flex = true,
--        bPointShop = true,
--        isdpoint = true,
--        price = 200,
--        vpos = Vector(0,0,69)
--    },
--
--    ["warmcap"] = {
--        model = "models/distac/warmcap.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,-0.95,0),Angle(180,100,90),1},
--        fempos = {Vector(0,0,0),Angle(0,0,0),1},
--        skin = 0,
--        norender = true,
--        bonemerge = true,
--        placement = "head",
--        flex = true,
--        bPointShop = true,
--        isdpoint = false,
--        price = 300,
--        vpos = Vector(0,0,69)
--    },
--    -- SCUGS!!!
--    ["slugcat"] = {
--        model = "models/salat_port/slugcat_figure.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = false,
--        placement = "spine",
--        bodygroups = "0",
--        bPointShop = true,
--        isdpoint = true,
--        price = 100,
--        vpos = Vector(0,0,0)
--    },
--    ["slugcat monk"] = {
--        model = "models/salat_port/slugcat_figure.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(0.6,5,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = false,
--        placement = "spine",
--        bodygroups = "1",
--        bPointShop = true,
--        isdpoint = true,
--        price = 100,
--        vpos = Vector(0,0,0)
--    },
--    ["slugcat gourmand"] = {
--        model = "models/salat_port/slugcat_figure.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = false,
--        placement = "spine",
--        bodygroups = "2",
--        bPointShop = true,
--        isdpoint = true,
--        price = 100,
--        vpos = Vector(0,0,0)
--    },
--    ["slugcat arti"] = {
--        model = "models/salat_port/slugcat_figure.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = false,
--        placement = "spine",
--        bodygroups = "3",
--        bPointShop = true,
--        isdpoint = true,
--        price = 100,
--        vpos = Vector(0,0,0)
--    },
--    ["slugcat rivulet"] = {
--        model = "models/salat_port/slugcat_figure.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = false,
--        placement = "spine",
--        bodygroups = "4",
--        bPointShop = true,
--        isdpoint = true,
--        price = 100,
--        vpos = Vector(0,0,0)
--    },
--    ["slugcat speermaster"] = {
--        model = "models/salat_port/slugcat_figure.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = false,
--        placement = "spine",
--        bodygroups = "5",
--        bPointShop = true,
--        isdpoint = true,
--        price = 100,
--        vpos = Vector(0,0,0)
--    },
--    ["slugcat saint"] = {
--        model = "models/salat_port/slugcat_figure.mdl",
--        bone = "ValveBiped.Bip01_Spine4",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = false,
--        placement = "spine",
--        bodygroups = "6",
--        bPointShop = true,
--        isdpoint = true,
--        price = 100,
--        vpos = Vector(0,0,0)
--    },
--    ["headband"] = {
--        model = "models/distac/headband.mdl",
--        femmodel = "models/distac/headband_f.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 0,
--        norender = false,
--        placement = "head",
--        norender = true,
--        bonemerge = true,
--        bPointShop = true,
--        isdpoint = false,
--        price = 100,
--        vpos = Vector(0,0,69)
--    },
--    ["occluder"] = {
--        model = "models/distac/occluder.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = true,
--        bonemerge = false,
--        placement = "face",
--        bPointShop = true,
--        isdpoint = false,
--        price = 250,
--        vpos = Vector(0,0,69)
--    },
--    ["headband kamikadze"] = {
--        model = "models/distac/headband.mdl",
--        femmodel = "models/distac/headband_f.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = false,
--        placement = "head",
--        norender = true,
--        bonemerge = true,
--        bPointShop = true,
--        isdpoint = false,
--        price = 150,
--        vpos = Vector(0,0,69)
--    },
--
--    ["mfdoom mask"] = {
--        model = "models/distac/mfdoom.mdl",
--        femmodel = "models/distac/mfdoom.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = false,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bPointShop = true,
--        isdpoint = true,
--        price = 200,
--        vpos = Vector(0,0,69)
--    },
--
--    ["hood"] = {
--        model = "models/distac/kapishon.mdl",
--        femmodel = "models/distac/kapishon.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.2,4.8,0),Angle(0,90,90),1},
--        fempos = {Vector(-1.2,3.5,0),Angle(0,90,90),1},
--        skin = 1,
--        norender = false,
--        placement = "head",
--        norender = true,
--        bonemerge = true,
--        bSetColor = true,
--        bPointShop = true,
--        isdpoint = true,
--        price = 100,
--        vpos = Vector(0,0,69)
--    },
--
--    ["christmas hat"] = {
--        model = "models/grinchfox/head_wear/christmas_hat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(2,0.5,0),Angle(180,90,90),1},
--        fempos = {Vector(0.2,0,0),Angle(180,90,90),1},
--        skin = 0,
--        norender = false,
--        placement = "head",
--        norender = true,
--        bonemerge = true,
--        bSetColor = true
--    },
--
--    ["cap deeper"] = {
--        model = "models/grinchfox/head_wear/caphat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(1,0.4,0),Angle(0,-95,-90),1},
--        fempos = {Vector(0,0.1,0),Angle(0,-95,-90),1},
--        skin = 7,
--        norender = false,
--        placement = "head",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 250,
--        vpos = Vector(0,0,5)
--    },
--
--    ["cap nurse"] = {
--        model = "models/grinchfox/head_wear/caphat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(1,0.4,0),Angle(0,-95,-90),1},
--        fempos = {Vector(0,0.1,0),Angle(0,-95,-90),1},
--        skin = 9,
--        norender = false,
--        placement = "head",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 100,
--        vpos = Vector(0,0,5)
--    },
--
--    ["deal glasses"] = {
--        model = "models/grinchfox/head_wear/dealglasses_fix.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.6,0.5,0),Angle(0,-90,-90),1.1},
--        fempos = {Vector(-0.5,.5,0),Angle(0,-90,-90),1.1},
--        skin = 0,
--        norender = true,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 400,
--        vpos = Vector(0,0,5)
--    },
--
--    ["cool glasses"] = {
--        model = "models/grinchfox/head_wear/fancyglasses2.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.6,0.2,0),Angle(0,-90,-90),1.1},
--        fempos = {Vector(-0.5,.2,0),Angle(0,-90,-90),1.1},
--        skin = 0,
--        norender = true,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 750,
--        vpos = Vector(0,0,5)
--    },
--
--    ["retro glasses"] = {
--        model = "models/grinchfox/head_wear/fancyglasses3.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.6,0.2,0),Angle(0,-90,-90),1.1},
--        fempos = {Vector(-0.5,.2,0),Angle(0,-90,-90),1.1},
--        skin = 0,
--        norender = true,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 500,
--        vpos = Vector(0,0,5)
--    },
--
--    ["tophat white"] = {
--        model = "models/grinchfox/head_wear/tophat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(2,0.4,0),Angle(0,-95,-90),1},
--        fempos = {Vector(1,0.1,0),Angle(0,-95,-90),1},
--        skin = 1,
--        norender = false,
--        placement = "head",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 200,
--        vpos = Vector(0,0,5)
--    },
--
--    ["bandana white"] = {
--        model = "models/grinchfox/head_wear/gangwrap.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.5,-0.1,0),Angle(0,-90,-90),1.15},
--        fempos = {Vector(-0.5,-0.5,0),Angle(0,-90,-90),1.05},
--        skin = 0,
--        norender = false,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 250,
--        vpos = Vector(0,0,0)
--    },
--
--    ["bandana groove"] = {
--        model = "models/grinchfox/head_wear/gangwrap.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.5,-0.1,0),Angle(0,-90,-90),1.15},
--        fempos = {Vector(-0.5,-0.5,0),Angle(0,-90,-90),1.05},
--        skin = 3,
--        norender = false,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = false,
--        price = 350,
--        vpos = Vector(0,0,0)
--    },
--
--    ["bandana crips"] = {
--        model = "models/grinchfox/head_wear/gangwrap.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.5,-0.1,0),Angle(0,-90,-90),1.15},
--        fempos = {Vector(-0.5,-0.5,0),Angle(0,-90,-90),1.05},
--        skin = 1,
--        norender = false,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = false,
--        price = 350,
--        vpos = Vector(0,0,0)
--    },
--
--    ["bandana white"] = {
--        model = "models/grinchfox/head_wear/gangwrap.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.5,-0.1,0),Angle(0,-90,-90),1.15},
--        fempos = {Vector(-0.5,-0.5,0),Angle(0,-90,-90),1.05},
--        skin = 0,
--        norender = false,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = false,
--        price = 250,
--        vpos = Vector(0,0,0)
--    },
--
--    ["bandana ghost"] = {
--        model = "models/grinchfox/head_wear/gangwrap.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.5,-0.1,0),Angle(0,-90,-90),1.15},
--        fempos = {Vector(-0.5,-0.5,0),Angle(0,-90,-90),1.05},
--        skin = 10,
--        norender = false,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 400,
--        vpos = Vector(0,0,0)
--    },
--
--    ["bandana hm"] = {
--        model = "models/grinchfox/head_wear/gangwrap.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.5,-0.1,0),Angle(0,-90,-90),1.15},
--        fempos = {Vector(-0.5,-0.5,0),Angle(0,-90,-90),1.05},
--        skin = 11,
--        norender = false,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 300,
--        vpos = Vector(0,0,0)
--    },
--
--    ["bandana evil"] = {
--        model = "models/grinchfox/head_wear/gangwrap.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(0.5,-0.1,0),Angle(0,-90,-90),1.15},
--        fempos = {Vector(-0.5,-0.5,0),Angle(0,-90,-90),1.05},
--        skin = 5,
--        norender = false,
--        placement = "face",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 300,
--        vpos = Vector(0,0,0)
--    },
--
--    ["baseball hub"] = {
--        model = "models/grinchfox/head_wear/baseballhat.mdl",
--        bone = "ValveBiped.Bip01_Head1",
--        malepos = {Vector(1,0.4,0),Angle(0,-95,-90),1.1},
--        fempos = {Vector(0,0.1,0),Angle(0,-95,-90),1},
--        skin = 6,
--        norender = false,
--        placement = "head",
--        norender = true,
--        bonemerge = true,
--        bSetColor = false,
--        bPointShop = true,
--        isdpoint = true,
--        price = 250,
--        vpos = Vector(0,0,5)
--    },
--
--}
--
----RunConsoleCommand("hg_appearance_menu")
--
--hook.Add("Think","RemoveME",function()
--    hg.PointShop = hg.PointShop or {}
--
--    local PLUGIN = hg.PointShop
--
--    PLUGIN.Items = {}
--
--    --PLUGIN:CreateItem( uid, strName, strModel, strBodyGroups, iSkin, vecPos, intPrice, bIsDPoints, tData, fCallback )
--
--    for k, acces in pairs(hg.Accessories) do
--        if not acces.bPointShop then continue end
--
--        PLUGIN:CreateItem( k, string.NiceName( k ), acces.model, acces.bodygroups, acces.skin, acces.vpos or Vector(0,0,0), acces.price, acces.isdpoint )
--    end
--    
--    hook.Remove( "Think", "RemoveME" )
--end)


--[[HMCD_Accessories={
	["none"]={},
	["eyeglasses"]={"models/captainbigbutt/skeyler/accessories/glasses01.mdl","ValveBiped.Bip01_Head1",{Vector(2.1,3,0),Angle(0,-70,-90),.9},{Vector(2.75,2,0),Angle(0,-70,-90),.8},false,0},
	["bugeye sunglasses"]={"models/captainbigbutt/skeyler/accessories/glasses02.mdl","ValveBiped.Bip01_Head1",{Vector(2.9,2.2,0),Angle(0,-70,-90),.9},{Vector(3.5,1.25,0),Angle(0,-70,-90),.8},false,0},
	["large sunglasses"]={"models/captainbigbutt/skeyler/accessories/glasses04.mdl","ValveBiped.Bip01_Head1",{Vector(3.25,2.4,0),Angle(0,-70,-90),.9},{Vector(3.5,1.25,0),Angle(0,-70,-90),.8},false,0},
	["aviators"]={"models/gmod_tower/aviators.mdl","ValveBiped.Bip01_Head1",{Vector(2.2,2.9,0),Angle(0,-75,-90),.9},{Vector(2.8,1.9,0),Angle(0,-75,-90),.85},false,0},
	["nerd glasses"]={"models/gmod_tower/klienerglasses.mdl","ValveBiped.Bip01_Head1",{Vector(2.6,2.9,0),Angle(0,-75,-90),1},{Vector(2.6,2.3,0),Angle(0,-80,-90),.9},false,0},
	["headphones"]={"models/gmod_tower/headphones.mdl","ValveBiped.Bip01_Head1",{Vector(.5,3,0),Angle(0,-90,-90),.9},{Vector(1,2.3,0),Angle(0,-90,-90),.8},false,0},
	["baseball cap"]={"models/gmod_tower/jaseballcap.mdl","ValveBiped.Bip01_Head1",{Vector(.05,5.1,0),Angle(0,-75,-90),1.125},{Vector(0,4.2,0),Angle(0,-75,-90),1.1},true,0},
	["fedora"]={"models/captainbigbutt/skeyler/hats/fedora.mdl","ValveBiped.Bip01_Head1",{Vector(.25,5.5,0),Angle(0,-75,-90),.7},{Vector(0,4.8,0),Angle(0,-75,-90),.65},true,0},
	["stetson"]={"models/captainbigbutt/skeyler/hats/cowboyhat.mdl","ValveBiped.Bip01_Head1",{Vector(.3,6,0),Angle(0,-70,-90),.75},{Vector(.25,5.6,0),Angle(0,-75,-90),.7},true,0},
	["straw hat"]={"models/captainbigbutt/skeyler/hats/strawhat.mdl","ValveBiped.Bip01_Head1",{Vector(.75,5,0),Angle(0,-75,-90),.85},{Vector(.5,4.5,0),Angle(0,-75,-90),.75},true,0},
	["sun hat"]={"models/captainbigbutt/skeyler/hats/sunhat.mdl","ValveBiped.Bip01_Head1",{Vector(-1.5,3.5,0),Angle(0,-75,-90),.8},{Vector(-1.5,3,0),Angle(0,-75,-90),.75},true,0},
	["bling cap"]={"models/captainbigbutt/skeyler/hats/zhat.mdl","ValveBiped.Bip01_Head1",{Vector(.7,3.75,.3),Angle(0,-75,-90),.75},{Vector(.3,3,.25),Angle(0,-75,-90),.75},true,0},
	["top hat"]={"models/player/items/humans/top_hat.mdl","ValveBiped.Bip01_Head1",{Vector(2,-1,0),Angle(0,-80,-90),1.025},{Vector(2,-1,0),Angle(0,-80,-90),.95},true,0},
	["backpack"]={"models/makka12/bag/jag.mdl","ValveBiped.Bip01_Spine4",{Vector(0,-3,0),Angle(0,90,90),.7},{Vector(.5,-3,0),Angle(0,90,90),.6},false,0},
	["purse"]={"models/props_c17/BriefCase001a.mdl","ValveBiped.Bip01_Spine1",{Vector(-3,-10,7),Angle(0,90,90),.6},{Vector(-3,-10,7),Angle(0,90,90),.6},false,0},
	-- gen 2
	["gray cap"]={"models/modified/hat07.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4.5,.2),Angle(0,-75,-90),1},{Vector(0,4.5,0),Angle(0,-75,-90),.95},true,0},
	["light gray cap"]={"models/modified/hat07.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4.5,.2),Angle(0,-75,-90),1},{Vector(0,4.5,0),Angle(0,-75,-90),.95},true,2},
	["white cap"]={"models/modified/hat07.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4.5,.2),Angle(0,-75,-90),1},{Vector(0,4.5,0),Angle(0,-75,-90),.95},true,3},
	["green cap"]={"models/modified/hat07.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4.5,.2),Angle(0,-75,-90),1},{Vector(0,4.5,0),Angle(0,-75,-90),.95},true,4},
	["dark green cap"]={"models/modified/hat07.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4.5,.2),Angle(0,-75,-90),1},{Vector(0,4.5,0),Angle(0,-75,-90),.95},true,5},
	["brown cap"]={"models/modified/hat07.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4.5,.2),Angle(0,-75,-90),1},{Vector(0,4.5,0),Angle(0,-75,-90),.95},true,6},
	["blue cap"]={"models/modified/hat07.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4.5,.2),Angle(0,-75,-90),1},{Vector(0,4.5,0),Angle(0,-75,-90),.95},true,7},

	["bandana"]={"models/modified/bandana.mdl","ValveBiped.Bip01_Head1",{Vector(1.1,-1.2,0),Angle(0,-75,-90),1},{Vector(1,-1.5,0),Angle(0,-80,-90),.9},false,0},

	["white scarf"]={"models/sal/acc/fix/scarf01.mdl","ValveBiped.Bip01_Spine4",{Vector(-10,-17,0),Angle(0,70,90),1},{Vector(-9,-19.5,0),Angle(0,70,90),1},false,0},
	["gray scarf"]={"models/sal/acc/fix/scarf01.mdl","ValveBiped.Bip01_Spine4",{Vector(-10,-17,0),Angle(0,70,90),1},{Vector(-9,-19.5,0),Angle(0,70,90),1},false,1},
	["black scarf"]={"models/sal/acc/fix/scarf01.mdl","ValveBiped.Bip01_Spine4",{Vector(-10,-17,0),Angle(0,70,90),1},{Vector(-9,-19.5,0),Angle(0,70,90),1},false,2},
	["blue scarf"]={"models/sal/acc/fix/scarf01.mdl","ValveBiped.Bip01_Spine4",{Vector(-10,-17,0),Angle(0,70,90),1},{Vector(-9,-19.5,0),Angle(0,70,90),1},false,3},
	["red scarf"]={"models/sal/acc/fix/scarf01.mdl","ValveBiped.Bip01_Spine4",{Vector(-10,-17,0),Angle(0,70,90),1},{Vector(-9,-19.5,0),Angle(0,70,90),1},false,4},
	["green scarf"]={"models/sal/acc/fix/scarf01.mdl","ValveBiped.Bip01_Spine4",{Vector(-10,-17,0),Angle(0,70,90),1},{Vector(-9,-19.5,0),Angle(0,70,90),1},false,5},
	["pink scarf"]={"models/sal/acc/fix/scarf01.mdl","ValveBiped.Bip01_Spine4",{Vector(-10,-17,0),Angle(0,70,90),1},{Vector(-9,-19.5,0),Angle(0,70,90),1},false,6},

	["red earmuffs"]={"models/modified/headphones.mdl","ValveBiped.Bip01_Head1",{Vector(1,2.5,0),Angle(0,-90,-90),.9},{Vector(1,2,0),Angle(0,-90,-90),.9},false,0},
	["pink earmuffs"]={"models/modified/headphones.mdl","ValveBiped.Bip01_Head1",{Vector(1,2.5,0),Angle(0,-90,-90),.9},{Vector(1,2,0),Angle(0,-90,-90),.9},false,1},
	["green earmuffs"]={"models/modified/headphones.mdl","ValveBiped.Bip01_Head1",{Vector(1,2.5,0),Angle(0,-90,-90),.9},{Vector(1,2,0),Angle(0,-90,-90),.9},false,2},
	["yellow earmuffs"]={"models/modified/headphones.mdl","ValveBiped.Bip01_Head1",{Vector(1,2.5,0),Angle(0,-90,-90),.9},{Vector(1,2,0),Angle(0,-90,-90),.9},false,3},

	["gray fedora"]={"models/modified/hat01_fix.mdl","ValveBiped.Bip01_Head1",{Vector(-.1,4.1,0),Angle(0,-75,-90),.9},{Vector(-.5,4,0),Angle(0,-75,-90),.9},true,0},
	["black fedora"]={"models/modified/hat01_fix.mdl","ValveBiped.Bip01_Head1",{Vector(-.1,4.1,0),Angle(0,-75,-90),.9},{Vector(-.5,4,0),Angle(0,-75,-90),.9},true,1},
	["white fedora"]={"models/modified/hat01_fix.mdl","ValveBiped.Bip01_Head1",{Vector(-.1,4.1,0),Angle(0,-75,-90),.9},{Vector(-.5,4,0),Angle(0,-75,-90),.9},true,2},
	["beige fedora"]={"models/modified/hat01_fix.mdl","ValveBiped.Bip01_Head1",{Vector(-.1,4.1,0),Angle(0,-75,-90),.9},{Vector(-.5,4,0),Angle(0,-75,-90),.9},true,3},
	["black/red fedora"]={"models/modified/hat01_fix.mdl","ValveBiped.Bip01_Head1",{Vector(-.1,4.1,0),Angle(0,-75,-90),.9},{Vector(-.5,4,0),Angle(0,-75,-90),.9},true,5},
	["blue fedora"]={"models/modified/hat01_fix.mdl","ValveBiped.Bip01_Head1",{Vector(-.1,4.1,0),Angle(0,-75,-90),.9},{Vector(-.5,4,0),Angle(0,-75,-90),.9},true,7},

	["striped beanie"]={"models/modified/hat03.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4,0),Angle(0,-75,-90),1},{Vector(-.2,3.5,0),Angle(0,-75,-90),1},true,0},
	["periwinkle beanie"]={"models/modified/hat03.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4,0),Angle(0,-75,-90),1},{Vector(-.2,3.5,0),Angle(0,-75,-90),1},true,1},
	["fuschia beanie"]={"models/modified/hat03.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4,0),Angle(0,-75,-90),1},{Vector(-.2,3.5,0),Angle(0,-75,-90),1},true,2},
	["white beanie"]={"models/modified/hat03.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4,0),Angle(0,-75,-90),1},{Vector(-.2,3.5,0),Angle(0,-75,-90),1},true,3},
	["gray beanie"]={"models/modified/hat03.mdl","ValveBiped.Bip01_Head1",{Vector(.1,4,0),Angle(0,-75,-90),1},{Vector(-.2,3.5,0),Angle(0,-75,-90),1},true,4},

	["large red backpack"]={"models/modified/backpack_1.mdl","ValveBiped.Bip01_Spine4",{Vector(-2,-8,0),Angle(0,90,90),1},{Vector(-2,-8,0),Angle(0,90,90),.9},false,0},
	["large gray backpack"]={"models/modified/backpack_1.mdl","ValveBiped.Bip01_Spine4",{Vector(-2,-8,0),Angle(0,90,90),1},{Vector(-2,-8,0),Angle(0,90,90),.9},false,1},

	["medium backpack"]={"models/modified/backpack_3.mdl","ValveBiped.Bip01_Spine4",{Vector(-3,-6,0),Angle(0,90,90),.9},{Vector(-3,-6,0),Angle(0,90,90),.8},false,0},
	["medium gray backpack"]={"models/modified/backpack_3.mdl","ValveBiped.Bip01_Spine4",{Vector(-3,-6,0),Angle(0,90,90),.9},{Vector(-3,-6,0),Angle(0,90,90),.8},false,1}
}]]--